# Generated by Django 5.0.7 on 2024-07-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile')], max_length=50)),
                ('project_url', models.URLField()),
                ('scopes', models.TextField(help_text='Enter each URL in scope on a new line')),
                ('out_of_scope', models.TextField(help_text='Enter each URL out of scope on a new line')),
                ('source', models.CharField(choices=[('HackerOne', 'HackerOne'), ('Bugcrowd', 'Bugcrowd'), ('Other', 'Other')], max_length=50)),
                ('source_other', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
