# Generated by Django 5.0.7 on 2024-07-12 07:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdomain',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('date_fetched', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon.project')),
            ],
        ),
    ]
