# Generated by Django 5.0.7 on 2024-07-21 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recon', '0003_crawleddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_delivery_network', models.TextField(blank=True, null=True)),
                ('content_management_system', models.TextField(blank=True, null=True)),
                ('web_hosting_provider', models.TextField(blank=True, null=True)),
                ('who_is_lookup', models.TextField(blank=True, null=True)),
                ('web_server', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recon.project')),
            ],
        ),
    ]
